[dependencies]

[package]
  cjc-version = "0.50.3"
  compile-option = "-O2 --diagnostic-format=noColor"
  description = "charset encoder/decoder"
  link-option = ""
  name = "charset"
  output-type = "dynamic"
  src-dir = "src"
  target-dir = ""
  version = "0.0.2"
  package-configuration = {}
