/*
 * Copyright (c) Cangjie Library Team 2022-2022. All rights resvered.
 */

/**
 * @file
 * This file is about GB18030Encoder
 */

package charset.simplechinese

import charset.encoding.*

/**
 * The class is GB18030Encoder inherited from Encoder
 * @author @freeonsky
 * @since 0.28.4
 */
public class GB18030Encoder <: Encoder {

    /**
     * Encodes a string into a byte array
     *
     * @param str of String
     *
     * @return Type of Array<UInt8>
     * @since 0.28.4
     */
    public func encode(str:String): Array<UInt8>{
        let ref = Array<UInt8>()
        // TODO
        return ref
    }
}